stackcbs/posts/urls.py
from django.urls import path 

from .views import post_comment_create_and_list_view,like_unlike_post,PostDeleteView,PostUpdateView

app_name = 'posts'  #important

urlpatterns = [
    path('',post_comment_create_and_list_view, name='main-post-view'),#used in view for redirect
    path('liked/',like_unlike_post, name='like-post-view'), #use this name in main.html
    path('<pk>/delete/',PostDeleteView.as_view(), name='post-delete'), #this path expect the primary key , set in views
    path('<pk>/update/',PostUpdateView.as_view(), name='post-update'), #this path expect the primary key , set in views


]


#http://127.0.0.1:8000/profiles -- will already be defined in main.urls.py

stackcbs/profiles/urls.py
from django.urls import path 

from .views import my_profile_view


app_name = 'profiles'  #important

urlpatterns = [
    path('myprofile/',my_profile_view, name='my_profile_view'),
]


#http://127.0.0.1:8000/profiles -- will already be defined in main.urls.py

stackcbs/stackcbs/urls.py
from django.contrib import admin
from django.urls import path , include #important
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view,register_page,login_page
from .router import router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view,name='home_view'),
    path('profiles/',include('profiles.urls',namespace='profiles')), #namespace must match with app name in appurls.py
    path('posts/',include('posts.urls',namespace='posts')), #namespace must match with app name in appurls.py
    path('api/', include(router.urls)), #this will return all the apis url
    path('register/',register_page,name='register_page'),
    path('login/',login_page,name='login_page')
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

stackcbs/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}


{% block content %}
{{hello_t}}
<br>
{{user_t}}
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
        console.log('working')
    })
</script>
{% endblock scripts %}



stackcbs/templates/main/login.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}


{% block content %}
hello 
<form action="login_page", method="POST">
    {% csrf_token %}
    <input type="text", name= 'username'><br>

    <input type="text", name= 'password'><br>
    <button type="submit" ></button>
</form>
<div>
    {% for message in messages %}
    <h3>{{message}}</h3>
    {% endfor %}
</div>
{% endblock content %}

{% block scripts %}

{% endblock scripts %}



stackcbs/templates/main/navbar.html
{% url 'home_view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my_profile_view' as path_to_profile %}
<div class="ui inverted menu nav mb-7">
    <div class="ui container">
      <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} ui icon button teal item">
          <h3>STACK EXCHANGE</h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} ui icon button teal item">
          Possts
      </a>
      <a href="{{path_to_profile}}" class="{% if request.path == path_to_profile %}active{% endif %} ui icon button teal item">
        My Profile
    </a>
      {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button teal"> Tags
                  <i class="dropdown icon"></i>
                  <div class="menu">
                      <a href="" class="item">
                          All Profiles
                      </a>
                      <a href="" class="item">
                          Send Invites
                      </a>
                      <a href="" class="item">
                          Received Invites
                      </a>
                  </div>
               </div>
          </div>
               <div class="item">
                <form action="" method="GET">
                  <div class="ui action left icon input">
                  <input class="prompt" type="text" name='q' placeholder="Search using tags...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div>
          
              <a href="" class="item">
                   {{ request.user }}
              </a>
  
              <a href="" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>

stackcbs/templates/main/register.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}


{% block content %}
    <h3>hi hihihi</h3>
    <div class="ui segment">
    
    <h3>Welcome  to your registration  page</h3>
    <div class="ui grid">
    <div class="row">
        <div class='six wide column'>
        
            <div class="row mt-5">
                <button class="ui secondary button" id="modal-btn" > NEW TO US !! SIGN IN HERE!!</button>
            </div>
        </div>
        
    </div>
    </div>
    </div>
    
    
    <hr>
    
    <!---modal taken from UI Semantics-->
    <div class="ui modal mymodal">
        <i class="close icon"></i>
        <div class="header">
        </div>
        <div class="image content">
          <div class="ui medium image">
            <img src="{{profile.avatar.url}}">
          </div>
        <div class="description">
            <div class="ui header">please enter your username and password </div>
            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
    
        <div class="actions">
          <button type="submit" class="ui positive right labeled icon button">
            SUBMIT
            <i class="checkmark icon"></i>
          </button>
        </div>
            </form>
        </div>
        </div>
        </div>
    

{% endblock content %}

{% block scripts %}

{% endblock scripts %}

