stackcbs/posts/urls.py
from django.urls import path 

from .views import post_comment_create_and_list_view,like_unlike_post,PostDeleteView,PostUpdateView

app_name = 'posts'  #important

urlpatterns = [
    path('',post_comment_create_and_list_view, name='main-post-view'),#used in view for redirect
    path('liked/',like_unlike_post, name='like-post-view'), #use this name in main.html
    path('<pk>/delete/',PostDeleteView.as_view(), name='post-delete'), #this path expect the primary key , set in views
    path('<pk>/update/',PostUpdateView.as_view(), name='post-update'), #this path expect the primary key , set in views


]


#http://127.0.0.1:8000/profiles -- will already be defined in main.urls.py

stackcbs/stackcbs/urls.py
from django.contrib import admin
from django.urls import path , include #important
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view,register_page,login_page
from .router import router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view,name='home_view'),
    path('profiles/',include('profiles.urls',namespace='profiles')), #namespace must match with app name in appurls.py
    path('posts/',include('posts.urls',namespace='posts')), #namespace must match with app name in appurls.py
    path('api/', include(router.urls)), #this will return all the apis url
    path('register/',register_page,name='register_page'),
    path('login/',login_page,name='login_page')
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

stackcbs/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile

# Create your models here.
class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['png','jpg','jpeg'])],blank=True)
    liked = models.ManyToManyField(Profile,blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile,on_delete=models.CASCADE, related_name='posts')  

    def __str__(self):
        return str(self.content[:20])

    def num_likes(self):
        return self.liked.all().count()

        #no of comments here
    def num_comments(self):
        return self.comment_set.all().count()    
        #we deal here with reverse relationship, in post we dont have any
        #relationship to comment but in comment we do have post
        #if we dint provided th related name by the post here
        #we need to write the model name and set 


    class Meta:
        ordering = ('-created',)   #newest on the top 


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('Like','Like'),   #one for processing and one for admin
    ('Unlike','Unlike',)
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}" 


   
    

stackcbs/posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs = {'rows':3}))
    class Meta:     #indicate the model
        model = Post
        fields = ('content',)
        #fields = ('content','image')

class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label = "", widget=forms.TextInput(attrs = {'placeholder':"Add you replies here.."}))
    class Meta:
        model = Comment
        fields = ('body',)

  

stackcbs/posts/views.py
from django.shortcuts import render,redirect
from .models import Post,Like
from profiles.models import Profile
from .forms import PostModelForm,CommentModelForm
from django.views.generic import UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

@login_required
def post_comment_create_and_list_view(request):
    qs = Post.objects.all()
    profile = Profile.objects.get(user=request.user)
    
    

    #post froms and comment form and initials 
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_added = False                   # when we submit post we ll set it to true
    print('post_added',post_added)
    profile = Profile.objects.get(user=request.user)
    
    if 'submit_p_form' in request.POST:
        print(33333)
        p_form = PostModelForm(request.POST,request.FILES)
        if p_form.is_valid():
            print(44444)
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_added = True

    if 'submit_c_form' in request.POST:
        post_added = False
        print(111)
        c_form = CommentModelForm(request.POST) 
        if c_form.is_valid():
            print(222)
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm() 
    print(post_added)
    context = {
        'qs':qs,
        'profile':profile,
        'p_form' : p_form,
        'c_form' : c_form,
        'post_added':post_added,

    }

    return render(request,'posts/main.html',context)

@login_required
def like_unlike_post(request):
    user = request.user
    if request.method == "POST":
        post_id = request.POST.get('post_id') #now we know to which post we are dealin
        post_obj = Post.objects.get(id=post_id)#post object 
        #now we need check for many to many field of posts to profile oif user 
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)  #if already liked then remove this profile 
        else:
            post_obj.liked.add(profile)
        


        like,created = Like.objects.get_or_create(user=profile,post_id=post_id) 
        #like is the object , created is the boolean value 
        if not created:
            if like.value=='Like':
                like.value = 'Unlike'
            else:
                like.value='Like'
        else:
            like.value='Like'    

            post_obj.save()
            like.save()    
    return redirect('posts:main-post-view')

class PostDeleteView(LoginRequiredMixin,DeleteView): #login must be firts parameter    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('posts:main-post-view')  #first app name , name of our path from url
    #success_url = '/posts/'  #this will give the same above result

    def get_object(self,*args,**kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request,'you need to be author of this post in order to delete this ')
        return obj

class PostUpdateView(LoginRequiredMixin,UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/Update.html'
    success_url = reverse_lazy('posts:main-post-view')  #first app name , name of our path from url
    #success_url = '/posts/'  #this will give the same above result

    def form_valid(self,form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None,"you need to be author to update")  
            return super().form_invalid(form) 

stackcbs/posts/templates/posts/confirm_del.html
{% extends 'base.html' %}

{% block title %}
confirm Delete posts
{% endblock title %}


{% block content %}

<!--first we need to check if any messages exist from view-->

{% if messages %}
    {% for message in messages %}
        {% if 'warning' in message.tags %}
            <div class="ui negative message">
                <div class="header">
                    {{message}}
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

{% if not messages %}
        <div class="ui segment">
            <h3>Delete POsts??</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delte this</p>
                <button type="submit" class="">submit</button>
            </form>
        </div>
{% endif %}

{% endblock content %}

{% block scripts %}

{% endblock scripts %}





stackcbs/posts/templates/posts/main.html

{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in qs %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% ifequal request.user obj.author.user %} <!--as we are in loop we can pass the pk as obj.pk-->
                            <a href="{% url 'posts:post-update' obj.pk %}"><button class="ui button bwhite-lg ">Update</button></a>
                            <a href="{% url 'posts:post-delete' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>
                    
                </div>
                <!--user, image and post created time we can use obj.author.user if want to get rid of craeted time attached-->
                <img class="ui avatar image" src={{obj.author.avatar.url}}> 
                {{ obj.author.user}} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form action="{% url 'posts:like-post-view' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        {% if profile not in obj.liked.all %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs up icon"></i>
                            </button>
                            <span> {{obj.num_likes}} likes</span>
                        {% else %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs down icon"></i>
                            </button>
                            <span> {{obj.num_likes}} likes</span>
                        {% endif %}
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ obj.num_comments }} Answers</span>
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <!--comment section,  using javascript here-->
                <!-- cmt_btn class triggers a js function -->
                <button class="cmt_btn ui button mb-5">show / hide Answers</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ c_form }}
                    <button type="submit" name="submit_c_form" class="ui primary button mt-5 w-full">reply</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if post_added %}
                <div class="ui green message">your question submitted successfully !!</div>
            {% endif %}
            <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{p_form}}
                <p></p>
                <button type='submit' name="submit_p_form" class="ui positive button w-full mt-5">Ask Your Question Here </button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false  //as display = none set in css file
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow"); //slow is animation effect
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });
        });
    </script>
{% endblock scripts %}

stackcbs/posts/templates/posts/main1.html
{% extends 'base.html' %}

{% block title %}
Posts
{% endblock title %}


{% block content %}
<div class="ui grid">
    <div class="row">
        <div class="eleven wide column">
            {% for obj in qs %}
            <div class="ui fluid card">
                <div class="content">
            <p>{{obj.content}}</p>
            
        </div>
        
        <div class="content">
            <form action="{% url 'posts:like-post-view' %}" method="POST">{%csrf_token%}
                <input type="hidden" name='post_id' value={{obj.id}}>
            <button type="submit" class="ui primary button">

            {% if profile not in obj.liked.all %}
            <i class="thumbs up icon"></i>&nbsp;{{obj.num_likes}}&nbsp;Like
            {% else %}
            <i class="thumbs down icon"></i>&nbsp;UnLike
            {% endif %}

            </button>
            &nbsp;{{obj.num_likes}}
        </form>
        </div>   
        <div>
            {% if obj.comment_set.all %}
            {% for c in obj.comment_set.all %}
            <p>{{c.body}}</p>
            {% endfor %}
            {% endif %}
        </div>
        
        <form action="" method="POST" class="ui form">
            {%csrf_token%}
            <input type="hidden" name="post_id" value={{obj.id}}>
            {{c_form}}
            <button type="submit" class="ui primary button" name="submit_c_form">Your Answer</button>
        </form>
            </div>
            {% endfor %}
        </div>
        <div class="five wide column">
            {%if post_added  %}
            <div class="ui green message">your Question Submitted ! </div>
            {% endif %}
            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{p_form}}
            <p></p>
            <button type="submit" class="ui button positive" name="submit_p_form">Ask You Questions here</button>
            </form>
            
        </div>
</div>
</div>
{% endblock content %}






stackcbs/posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
Update posts
{% endblock title %}


{% block content %}

<div class="ui segment">
    <h3>Update POst</h3>
    <form action="" method="POST" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="ui button primary mt-5">Update</button>
    </form>

</div>


{% endblock content %}

{% block scripts %}

{% endblock scripts %}



